# Prettier Configuration
# https://prettier.io/docs/en/options

printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: false
quoteProps: as-needed
trailingComma: all
bracketSpacing: true
bracketSameLine: false
arrowParens: always
proseWrap: never
endOfLine: lf
embeddedLanguageFormatting: auto
singleAttributePerLine: false
overrides:
  - files:
      - "*.{html,vue}"
      - "*.{css,scss,less}"
      - "*.{js,jsx,mjs,cjs,ts,tsx,mts,cts}"
    options:
      singleQuote: true
      jsxSingleQuote: true
