# Prettier Configuration
# https://prettier.io/docs/en/options

printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
jsxSingleQuote: false
quoteProps: as-needed
trailingComma: all
bracketSpacing: true
bracketSameLine: false
arrowParens: always
proseWrap: never
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: false
endOfLine: lf
embeddedLanguageFormatting: auto
singleAttributePerLine: false
overrides:
  - files:
      - '*.{md,markdown}'
    options:
      singleQuote: false
